# Generated by Django 4.2.1 on 2024-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
