# Generated by Django 4.2.1 on 2024-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
